/**
 * The director's page (spec §9), German, vanilla JS over the JSON API in
 * server.ts. Guided: every view says what happens here, shows only the
 * fields the step needs, and keeps the rest behind "Details". Nothing here
 * talks to Venice, the text model or Jev directly.
 */
export const DIRECTOR_HTML = String.raw`<!doctype html>
<html lang="de"><head><meta charset="utf-8"><title>Venice Director</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
:root{--bg:#f6f6f4;--fg:#1c1c1a;--muted:#6b6b66;--line:#dcdcd6;--card:#fff;--green:#1f8a4c;--yellow:#c98a00;--red:#c0392b;--blue:#2a5db0;--soft:#eef3fb}
*{box-sizing:border-box}body{margin:0;font:15px/1.5 system-ui,sans-serif;background:var(--bg);color:var(--fg)}
header{display:flex;gap:16px;align-items:center;padding:10px 16px;border-bottom:1px solid var(--line);background:#fff;position:sticky;top:0;z-index:2;flex-wrap:wrap}
header a{color:var(--blue);text-decoration:none;font-weight:600}header .cost{margin-left:auto;color:var(--muted);font-size:12px}
main{padding:16px;max-width:1100px;margin:0 auto}h1,h2,h3{margin:0 0 8px;font-weight:600}h1{font-size:22px}h2{font-size:18px;margin-top:24px}h3{font-size:15px}
.intro{background:var(--soft);border:1px solid #cfdcf3;border-radius:8px;padding:10px 14px;margin:8px 0 16px;color:#243b63}
.card{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:14px;margin-bottom:12px}
.row{display:flex;gap:12px;flex-wrap:wrap}.col{flex:1;min-width:240px}
label{display:block;font-size:13px;color:var(--muted);margin-top:10px}.hint{font-size:12px;color:var(--muted);margin:2px 0 0}
input,select,textarea{width:100%;padding:8px;border:1px solid var(--line);border-radius:6px;font:inherit;background:#fff}textarea{min-height:72px;resize:vertical}
button{padding:8px 14px;border:1px solid var(--line);border-radius:6px;background:#fff;font:inherit;cursor:pointer;margin:8px 8px 0 0}
button.primary{background:var(--blue);color:#fff;border-color:var(--blue)}button.big{font-size:16px;padding:12px 18px}button.danger{background:var(--red);color:#fff;border-color:var(--red)}button:disabled{opacity:.45;cursor:not-allowed}
details{margin-top:10px}summary{cursor:pointer;color:var(--blue);font-weight:600}
.board{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:8px}.lane{background:#eeeeea;border-radius:8px;padding:8px;min-height:90px}.lane h3{font-size:12px;text-transform:uppercase;color:var(--muted)}
.tile{background:#fff;border:1px solid var(--line);border-radius:6px;padding:8px;margin-bottom:6px;cursor:pointer}.tile:hover{border-color:var(--blue)}
.pill{display:inline-block;padding:1px 9px;border-radius:10px;font-size:12px;color:#fff;background:var(--muted)}.pill.green{background:var(--green)}.pill.yellow{background:var(--yellow)}.pill.red{background:var(--red)}.pill.block{background:var(--red)}.pill.warn{background:var(--yellow)}
table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:5px 8px;border-bottom:1px solid var(--line);vertical-align:top;font-size:13px}
pre{background:#f0f0ec;padding:8px;border-radius:6px;overflow:auto;font-size:12px;white-space:pre-wrap}.muted{color:var(--muted)}.err{color:var(--red);white-space:pre-wrap}.ok{color:var(--green)}
.thumbs{display:flex;gap:10px;flex-wrap:wrap;margin-top:8px}.thumb{width:120px;font-size:12px;text-align:center}.thumb img,.thumb video{width:120px;height:120px;object-fit:cover;border:1px solid var(--line);border-radius:6px;display:block}
.frames{display:flex;gap:8px;flex-wrap:wrap}.frames img{max-height:200px;border:1px solid var(--line)}.compare img{max-width:100%;border:1px solid var(--line)}
.toast{position:fixed;bottom:16px;right:16px;background:#1c1c1a;color:#fff;padding:12px 16px;border-radius:8px;max-width:560px;white-space:pre-wrap;display:none;z-index:9;font-size:14px}
.steps{display:flex;gap:6px;flex-wrap:wrap;margin:6px 0 12px}.step{padding:4px 10px;border-radius:12px;background:#e7e7e2;font-size:12px}.step.done{background:#d7ecdf}.step.now{background:var(--blue);color:#fff}
.inactive{opacity:.5}.small{font-size:12px}
</style></head><body>
<header><a href="#projects">Projekte</a><span id="nav"></span><span class="cost" id="cost"></span></header>
<main id="main"></main><div class="toast" id="toast"></div>
<script>
const $=(s,r=document)=>r.querySelector(s);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const STATUS=["draft","claude","gated","approved","queued","done","review","failed"];
const LANE={draft:"Neu",claude:"Entworfen",gated:"Geprüft",approved:"Freigegeben",queued:"Wird gerendert",done:"Fertig",review:"Im Review",failed:"Fehler"};
const WORKFLOWS=["t2v","i2v","r2v_reference","r2v_edit","r2v_extend","r2v_stitch"];const ROLES=["identity","keyframe","style","motion","audio"];
const ROLE_DE={identity:"Identität (Gesicht der Figur)",keyframe:"Startbild",style:"Look-Vorlage",motion:"Bewegungs-Vorlage (Video)",audio:"Audio"};
let STATE=null;
function toast(msg,ms=7000){const t=$("#toast");t.textContent=msg;t.style.display="block";clearTimeout(t._h);t._h=setTimeout(()=>t.style.display="none",ms)}
async function api(method,path,body,raw){const init={method,headers:{}};if(raw){init.body=raw}else if(body!==undefined){init.headers["content-type"]="application/json";init.body=JSON.stringify(body)}
 const r=await fetch(path,init);const j=await r.json().catch(()=>({error:"keine JSON-Antwort"}));if(!r.ok){throw new Error(j.error||("HTTP "+r.status))}return j}
async function loadState(){STATE=await api("GET","/api/state");const c={};for(const x of STATE.costs)c[x.kind]=x;const cap=STATE.capabilities;
 $("#cost").textContent="Ausgegeben: Venice "+((c.venice?.usd)||0).toFixed(3)+" USD"+((c.claude?.usd)?" · Anthropic "+c.claude.usd.toFixed(3)+" USD":"")+" · Jev "+((c.jev?.n)||0)+"× · "
 +(cap.text?"Text "+cap.textModel+" ✓":"kein Textmodell ✗")+" · "+(cap.gate?"Jev ✓":"Jev ✗")+" · "+(cap.venice?"Venice ✓":"Venice ✗")+" · "+(cap.ffmpeg?"ffmpeg ✓":"ffmpeg ✗")}
function field(label,name,value,type="input",opts,hint,placeholder){let h='<label>'+esc(label)+'</label>';
 if(type==="select")h+='<select name="'+name+'">'+opts.map(o=>'<option value="'+esc(o)+'"'+(String(o)===String(value)?" selected":"")+'>'+esc(o)+'</option>').join("")+'</select>';
 else if(type==="textarea")h+='<textarea name="'+name+'" placeholder="'+esc(placeholder||"")+'">'+esc(value)+'</textarea>';
 else h+='<input name="'+name+'" value="'+esc(value)+'" placeholder="'+esc(placeholder||"")+'">';
 if(hint)h+='<p class="hint">'+esc(hint)+'</p>';return h}
function engineFamily(id){return id.replace(/-(text|image|reference|video|first-last-frame)-to-video.*$/,"").replace(/-(basic|private)$/,"").replace(/-(multi-angle|motion-control|transition|text)$/,"")}
function engineSelect(label,name,value,hint){const groups={};for(const e of STATE.engines){const f=engineFamily(e.id);(groups[f]=groups[f]||[]).push(e)}
 const order=Object.keys(groups).sort((a,b)=>(b.startsWith("seedance")-a.startsWith("seedance"))||a.localeCompare(b));
 return '<label>'+esc(label)+'</label><select name="'+name+'">'+order.map(f=>'<optgroup label="'+esc(f)+'">'+groups[f].map(e=>'<option value="'+esc(e.id)+'"'+(e.id===value||e.id===value+"-basic"?" selected":"")+'>'+esc(e.id)+(e.source==="documented"?"":" ·")+'</option>').join("")+'</optgroup>').join("")+'</select>'+(hint?'<p class="hint">'+esc(hint)+'</p>':'')}
function formData(el){const o={};for(const i of el.querySelectorAll("[name]"))o[i.name]=i.value;return o}
const fileUrl=p=>"/files/"+encodeURIComponent(p);
function route(){const h=location.hash.slice(1)||"projects";const p=h.split("/");const v={projects:viewProjects,bible:viewBible,board:viewBoard,shot:viewShot,jobs:viewJobs,review:viewReview}[p[0]]||viewProjects;
 loadState().then(()=>v(...p.slice(1).map(Number))).catch(e=>{$("#main").innerHTML='<p class="err">'+esc(e.message)+'</p>'})}
window.addEventListener("hashchange",route);route();
function nav(pid){$("#nav").innerHTML=pid?'· <a href="#bible/'+pid+'">1 Figuren &amp; Look</a> · <a href="#board/'+pid+'">2 Shots</a> · <a href="#jobs/'+pid+'">3 Render-Jobs</a>':""}
const run=async(fn,msg,after)=>{try{if(msg)toast(msg,60000);const r=await fn();if(after)after(r);else route()}catch(x){toast("Fehler: "+x.message,15000)}};

// ---------- Projekte ----------
async function viewProjects(){nav();const m=$("#main");
 m.innerHTML='<h1>Projekte</h1><div class="intro">Ein Projekt ist ein Film. Darin: die Figuren mit Foto, der Look, und die Shots (kurze Clips von 5 oder 10 Sekunden). Aus jedem Shot wird ein Venice-Auftrag, den du vor dem Bezahlen freigibst.</div>'
 +STATE.projects.map(p=>'<div class="card"><a href="#bible/'+p.id+'" style="font-size:17px;font-weight:600">'+esc(p.name)+'</a> <span class="muted small">· '+esc(p.default_engine)+' · '+esc(p.default_resolution)+'</span></div>').join("")
 +'<div class="card"><h3>Neues Projekt</h3><form id="np">'+field("Name","name","","input",null,"Nur der Name. Format 16:9, 480p und Seedance 2.0 sind voreingestellt und lassen sich später ändern.","z. B. Mara am Fenster")+'<button class="primary">Projekt anlegen</button></form></div>';
 $("#np").onsubmit=e=>{e.preventDefault();run(()=>api("POST","/api/projects",formData(e.target)),null,p=>{location.hash="bible/"+p.id})}}

// ---------- Bibel ----------
async function viewBible(pid){nav(pid);const d=await api("GET","/api/projects/"+pid);const m=$("#main");const cap=STATE.capabilities;const refOf=id=>d.references.filter(r=>r.character_id===id);
 const ready=d.characters.length&&d.characters.every(c=>refOf(c.id).some(r=>r.kind==="image"));
 m.innerHTML='<h1>'+esc(d.project.name)+' · Schritt 1: Figuren &amp; Look</h1>'
 +'<div class="intro">Hier steht, was in jedem Clip gleich bleiben soll. <b>Pro Figur: ein Name, ein Satz zum Aussehen, ein Foto.</b> Das Foto ist die Identitätsreferenz, Venice hält damit das Gesicht über alle Clips. Der Look ist ein kurzer Text zu Farbe, Licht und Stimmung des ganzen Films. Englische Fassungen für das Videomodell entstehen beim Speichern automatisch'+(cap.text?"":" (im Moment aus, kein Textmodell)")+'.'
 +(ready?' <span class="ok">Alles da, du kannst zu <a href="#board/'+pid+'">Schritt 2: Shots</a>.</span>':'')+'</div>'
 +'<h2>Figuren</h2>'+(d.characters.length?'':'<p class="muted">Noch keine Figur. Lege unten die erste an.</p>')
 +d.characters.map(c=>'<div class="card"><div class="row"><div class="col"><form data-char="'+c.id+'">'+field("Name","name",c.name)+field("Aussehen, das immer gleich bleibt","fixed_attributes_de",c.fixed_attributes_de,"textarea",null,"Gesicht, Haare, Augen, feste Kleidung. Das Videomodell und die Prüfung nutzen genau das.","z. B. Frau Ende 20, rote lockige Haare, grüne Augen, Narbe über der linken Braue, dunkelblauer Wollmantel")
 +'<details><summary>Details</summary>'+field("Was sich ändern darf","variable_attributes",c.variable_attributes,"textarea",null,"z. B. Frisur offen oder gebunden, Stimmung, Accessoires")+field("Notizen","notes",c.notes,"textarea")+(c.fixed_attributes_en?'<p class="hint">Englisch: '+esc(c.fixed_attributes_en)+'</p>':'')+'</details><button class="primary">Speichern</button></form></div>'
 +'<div class="col"><label>Foto (Identitätsreferenz)</label><div class="thumbs">'+refOf(c.id).map(refTile).join("")+'</div>'+(refOf(c.id).some(r=>r.kind==="image")?'':'<p class="err">Ohne Foto kann diese Figur in keinem Shot vorkommen (Regel R1).</p>')
 +'<form data-upload="'+c.id+'"><input type="file" accept="image/*,video/*,audio/*"><p class="hint">Ein klares Porträt oder Ganzkörperbild, neutrales Licht. Weitere Bilder derselben Figur sind erlaubt.</p><button>Foto hochladen</button></form></div></div></div>').join("")
 +'<div class="card"><h3>Neue Figur</h3><form id="cf">'+field("Name","name","","input",null,"So, wie du die Figur in den Shots nennen wirst.","Mara")+field("Aussehen, das immer gleich bleibt","fixed_attributes_de","","textarea",null,null,"Frau Ende 20, rote lockige Haare, grüne Augen, Narbe über der linken Braue")+'<button class="primary">Figur anlegen</button><p class="hint">Das Foto lädst du danach bei der Figur hoch.</p></form></div>'
 +'<h2>Look des Films</h2><div class="card"><form id="pf">'+field("Look","style_guide_de",d.project.style_guide_de,"textarea",null,"Zwei, drei Sätze: Farben, Licht, Stimmung, Kamera-Ästhetik. Kommt als Stil-Abschnitt in jeden Prompt.","z. B. Gedeckte Farben, weiches Fensterlicht, leichtes Filmkorn, ruhige Kamera, nordisches Drama.")
 +(d.project.style_guide_en?'<p class="hint">Englisch: '+esc(d.project.style_guide_en)+'</p>':'')+'<details><summary>Voreinstellungen</summary>'+field("Seitenverhältnis","aspect_ratio",d.project.aspect_ratio,"select",["16:9","9:16","1:1","4:3","3:4","21:9"])+field("Auflösung","default_resolution",d.project.default_resolution,"select",["480p","720p","1080p"],"480p ist Standard: billig, schnell, Hochskalieren später (Regel R9).")+engineSelect("Engine","default_engine",d.project.default_engine,"Seedance 2.0 reference-to-video hält Gesichter über Referenzbilder. Einträge mit · haben geschätzte Limits.")+'</details><button class="primary">Look speichern</button></form></div>'
 +'<details class="card"><summary>Regeln der Bibel ('+d.rules.filter(r=>r.active).length+' aktiv)</summary><p class="hint">Diese Regeln prüfen Code und Jev vor jedem Auftrag. Aus dem Review kommen neue dazu. Abschalten nur mit Grund.</p><table>'+d.rules.map(r=>'<tr class="'+(r.active?"":"inactive")+'"><td><b>'+esc(r.code)+'</b> <span class="pill '+esc(r.severity)+'">'+(r.severity==="block"?"blockiert":"Hinweis")+'</span></td><td>'+esc(r.text_de)+'<br><span class="small muted">'+esc(r.check_type)+' · '+esc(r.origin)+'</span></td><td><button data-rule="'+r.id+'" data-active="'+(r.active?0:1)+'">'+(r.active?"aus":"an")+'</button></td></tr>').join("")+'</table>'
 +'<form id="rf">'+field("Neue Regel","text_de","","textarea",null,null,"z. B. Mara trägt nie eine Sonnenbrille.")+field("Schwere","severity","block","select",["block","warn"])+'<button>Regel hinzufügen</button></form></details>'
 +'<details class="card"><summary>Weitere Referenzen (Look-Vorlagen, Bewegungs-Videos, Startbilder)</summary><p class="hint">Nur nötig, wenn ein Shot einen bestimmten Look kopieren, einer Bewegung aus einem Video folgen oder von einem festen Startbild ausgehen soll.</p><div class="thumbs">'+d.references.filter(r=>!r.character_id).map(refTile).join("")+'</div><form data-upload=""><div class="row"><div class="col"><input type="file"></div><div class="col">'+field("Rolle","role","style","select",ROLES)+'</div><div class="col">'+field("Dauer in Sekunden (nur Video)","duration_s","")+'</div></div><button>Hochladen</button></form></details>';
 $("#pf").onsubmit=e=>{e.preventDefault();run(()=>api("PATCH","/api/projects/"+pid,formData(e.target)),cap.text?"speichere und übersetze …":null,r=>{if(r.translate_error)toast("Gespeichert, Übersetzung fehlgeschlagen: "+r.translate_error,12000);route()})};
 $("#rf").onsubmit=e=>{e.preventDefault();const o=formData(e.target);o.text_en="";run(()=>api("POST","/api/projects/"+pid+"/rules",o))};
 $("#cf").onsubmit=e=>{e.preventDefault();run(()=>api("POST","/api/projects/"+pid+"/characters",formData(e.target)),cap.text?"lege an und übersetze …":null)};
 for(const b of m.querySelectorAll("[data-rule]"))b.onclick=e=>{e.preventDefault();run(()=>api("PATCH","/api/rules/"+b.dataset.rule,{active:b.dataset.active==="1"}))};
 for(const f of m.querySelectorAll("[data-char]"))f.onsubmit=e=>{e.preventDefault();run(()=>api("PATCH","/api/characters/"+f.dataset.char,formData(f)),cap.text?"speichere und übersetze …":null,r=>{if(r.translate_error)toast("Gespeichert, Übersetzung fehlgeschlagen: "+r.translate_error,12000);route()})};
 for(const f of m.querySelectorAll("[data-upload]"))f.onsubmit=e=>{e.preventDefault();const file=f.querySelector("input[type=file]").files[0];if(!file)return toast("Erst eine Datei wählen");const o=formData(f);
  const q=new URLSearchParams({name:file.name,character_id:f.dataset.upload||""});if(o.role)q.set("role",o.role);if(o.duration_s)q.set("duration_s",o.duration_s);run(()=>api("PUT","/api/projects/"+pid+"/references?"+q,undefined,file),"lade hoch …")};
 for(const b of m.querySelectorAll("[data-consent]"))b.onclick=e=>{e.preventDefault();const t=prompt("Consent-Objekt (JSON) für diese Referenz, wie von Venice verlangt:");if(!t)return;run(()=>api("POST","/api/references/"+b.dataset.consent+"/consent",{consent:JSON.parse(t)}))}}
function refTile(r){const src=fileUrl(r.path);const media=r.kind==="image"?'<img src="'+esc(src)+'" alt="">':r.kind==="video"?'<video src="'+esc(src)+'" muted></video>':'<div class="muted">Audio</div>';
 return '<div class="thumb">'+media+esc(ROLE_DE[r.role_default]||r.role_default)+(r.duration_s?' · '+r.duration_s+' s':'')+'<br>'+(r.consent_json?'<span class="pill green">Consent</span>':'<button type="button" class="small" data-consent="'+r.id+'" title="Nur nötig, wenn Venice bei diesem Gesicht eine Einwilligung verlangt">Consent</button>')+'</div>'}

// ---------- Board ----------
async function viewBoard(pid){nav(pid);const d=await api("GET","/api/projects/"+pid);const m=$("#main");
 const noPhoto=d.characters.filter(c=>!d.references.some(r=>r.character_id===c.id&&r.kind==="image")).map(c=>c.name);
 m.innerHTML='<h1>'+esc(d.project.name)+' · Schritt 2: Shots</h1><div class="intro">Ein Shot ist ein Clip von 5 oder 10 Sekunden. <b>Du schreibst nur, was passiert, und nennst die Figur beim Namen.</b> Den Rest (Einstellungsgröße, Kamera, Licht, englischer Prompt, Referenzbilder) füllt die App auf der Shot-Karte aus. '+(d.characters.length?'':'<span class="err">Erst eine Figur mit Foto in Schritt 1 anlegen.</span>')+(noPhoto.length?'<span class="err">Ohne Foto: '+esc(noPhoto.join(", "))+'.</span>':'')+'</div>'
 +'<div class="card"><h3>Neuer Shot</h3><form id="sf">'+field("Was passiert?","beat_de","","textarea",null,"Ein bis zwei Sätze, Figur beim Namen, eine sichtbare Handlung mit Anfang und Ende.","z. B. Mara sitzt am Küchentisch, hebt die Tasse mit der rechten Hand, trinkt einen Schluck und stellt sie ab.")+'<div class="row"><div class="col">'+field("Dauer","duration_s","5","select",[5,10])+'</div><div class="col">'+field("Anschluss an den vorigen Shot","transition_in","hard_cut","select",["hard_cut","extend"],"hard_cut: neuer Clip. extend: der Clip setzt den vorigen direkt fort (braucht dessen fertiges Video).")+'</div></div><button class="primary big">Shot anlegen</button></form></div>'
 +'<h2>Alle Shots</h2><div class="board">'+STATUS.map(s=>{const list=d.shots.filter(x=>x.status===s);return list.length||s==="draft"?'<div class="lane"><h3>'+LANE[s]+'</h3>'+list.map(x=>'<div class="tile" onclick="location.hash=\'shot/'+x.id+'\'"><b>#'+x.seq+'</b> '+esc((x.beat_de||"(leer)").slice(0,90))+'</div>').join("")+'</div>':''}).join("")+'</div>';
 $("#sf").onsubmit=e=>{e.preventDefault();const o=formData(e.target);o.duration_s=Number(o.duration_s);if(!o.beat_de.trim())return toast("Schreib erst, was passiert.");run(()=>api("POST","/api/projects/"+pid+"/shots",o),null,s=>{location.hash="shot/"+s.id})}}

// ---------- Shot-Karte ----------
function nextStep(s,d,cap){if(s.status==="draft")return cap.text?"Drück „Entwurf erstellen“. Die App ordnet die Fotos der genannten Figuren zu, und das Textmodell füllt Kamera, Licht und die englische Handlung.":"Fülle unter „Felder bearbeiten“ Einstellungsgröße, Kamerabewegung und die englische Handlung aus (kein Textmodell konfiguriert), dann „Prüfen“.";
 if(s.status==="claude")return "Lies den Entwurf rechts. Wenn er passt: „Prüfen“. Das baut den Prompt und lässt Code"+(cap.gate?" und Jev":"")+" gegen die Regeln prüfen.";
 if(s.status==="gated"){const v=d.gate?.verdict;if(v==="green")return cap.venice?"Grün. „Angebot holen“ fragt Venice nach dem Preis. Bezahlt wird erst nach deiner Freigabe in Schritt 3.":"Grün, aber kein Venice-Schlüssel.";if(v==="yellow")return "Gelb: Jev ist sich bei einer Regel unsicher. „Korrigieren“ lässt das Textmodell nur die betroffenen Felder ändern, danach wieder „Prüfen“.";return "Rot: eine Regel ist verletzt, siehe Prüfung unten. Ändere Beat oder Felder, dann wieder „Prüfen“."}
 if(s.status==="approved")return "Freigegeben. In Schritt 3 „An Venice senden“.";if(s.status==="queued")return "Venice rendert. In Schritt 3 „Status abfragen“.";if(s.status==="done")return "Fertig gerendert, Review offen.";if(s.status==="review")return "Im Review: Clip neben Referenz prüfen und Pass oder Fail geben.";return "Fehlgeschlagen, siehe Job in Schritt 3."}
async function viewShot(id){const d=await api("GET","/api/shots/"+id);const s=d.shot;nav(s.project_id);const p=await api("GET","/api/projects/"+s.project_id);const m=$("#main");const V=STATE.vocabulary;const cap=STATE.capabilities;
 const idx=STATUS.indexOf(s.status);const steps=[["draft","Neu"],["claude","Entwurf"],["gated","Geprüft"],["approved","Freigegeben"],["queued","Rendern"],["done","Fertig"],["review","Review"]].map(([k,l],i)=>'<span class="step '+(i<idx?"done":i===idx?"now":"")+'">'+l+'</span>').join("");
 const gateHtml=d.gate?'<h3>Prüfung <span class="pill '+esc(d.gate.verdict)+'">'+({green:"grün",yellow:"gelb",red:"rot"})[d.gate.verdict]+'</span> <span class="small muted">'+esc(d.gate.jev_model)+' · '+new Date(d.gate.created_at).toLocaleString("de")+'</span></h3>'
  +'<table>'+d.gate.code_checks.filter(c=>!c.ok).map(c=>'<tr><td><span class="pill '+c.severity+'">'+esc(c.rule)+'</span></td><td>'+esc(c.detail)+'</td></tr>').join("")+Object.entries(d.gate.answers).map(([k,a])=>{const v=a.type==="noul"?"p(ja) "+a.noul.toFixed(2):a.type==="score"?"Score "+a.score.toFixed(2)+" · Sicherheit "+(a.confidence??0).toFixed(2):esc(a.choice)+" · Sicherheit "+(a.confidence??0).toFixed(2);return '<tr><td class="muted">'+esc(k)+'</td><td>'+v+'</td></tr>'}).join("")+'</table>'
  :(d.checks&&d.checks.length?'<h3>Code-Prüfung</h3><table>'+d.checks.map(c=>'<tr><td><span class="pill '+(c.ok?"green":c.severity)+'">'+esc(c.rule)+'</span></td><td>'+esc(c.detail)+'</td></tr>').join("")+'</table>':'<p class="muted">Noch nicht geprüft.</p>');
 const canFix=cap.text&&d.gate&&d.gate.verdict==="yellow";const canQuote=cap.venice&&d.gate&&d.gate.verdict==="green";
 m.innerHTML='<h1>Shot #'+s.seq+' <span class="muted" style="font-weight:400;font-size:15px">'+esc(s.beat_de.slice(0,80))+'</span></h1><div class="steps">'+steps+'</div>'
 +'<div class="intro"><b>Nächster Schritt:</b> '+nextStep(s,d,cap)+'</div>'+(s.review_note?'<div class="card err">Aus dem Review: '+esc(s.review_note)+'</div>':"")
 +'<div class="card"><button id="bprep" class="primary big" '+(cap.text?"":"disabled")+'>Entwurf erstellen</button><button id="bcheck" class="big">Prüfen</button><button id="bfix" class="big" '+(canFix?"":"disabled")+'>Korrigieren</button><button id="bquote" class="primary big" '+(canQuote?"":"disabled")+'>Angebot holen</button>'
 +'<p class="hint">Entwurf und Korrigieren kosten einen Textmodell-Aufruf (unter 1 Cent). Prüfen ist gratis'+(cap.gate?" bis auf den Jev-Aufruf":"")+'. Angebot holen ist gratis; Geld fließt erst nach deiner Freigabe in Schritt 3.</p></div>'
 +'<div class="row"><div class="col card"><h3>Handlung</h3><form id="beatf">'+field("Was passiert?","beat_de",s.beat_de,"textarea")+'<button class="primary">Speichern</button></form>'
 +'<h3 style="margin-top:14px">Referenzbilder</h3>'+(d.references.length?'<div class="thumbs">'+d.references.map(r=>'<div class="thumb">'+(r.reference.kind==="image"?'<img src="'+esc(fileUrl(r.reference.path))+'" alt="">':'<video src="'+esc(fileUrl(r.reference.path))+'" muted></video>')+esc(r.slot)+' · '+esc(r.subject_label||ROLE_DE[r.role]||r.role)+'</div>').join("")+'</div>':'<p class="muted">Werden beim Entwurf automatisch aus den im Beat genannten Figuren gesetzt.</p>')
 +'<details><summary>Referenzen von Hand setzen</summary><table id="reft"><tr><th>Slot</th><th>Datei</th><th>Rolle</th><th>Subjekt</th><th></th></tr>'+d.references.map((r,i)=>refRow(r,i,p.references)).join("")+'</table><button id="addref">Zeile</button> <button id="saveref" class="primary">Speichern</button><p class="hint">Bilder heißen Image 1, Image 2 …, Videos Video 1 … Startbild immer Image 1, Identität dahinter (R2).</p></details></div>'
 +'<div class="col card"><h3>Entwurf</h3>'+(s.shot_size||s.action_physical_en?'<table><tr><td class="muted">Einstellung</td><td>'+esc(s.shot_size)+'</td></tr><tr><td class="muted">Kamera</td><td>'+esc(s.camera_move)+'</td></tr><tr><td class="muted">Licht</td><td>'+esc(s.lighting)+'</td></tr><tr><td class="muted">Bild</td><td>'+esc(s.composition)+'</td></tr><tr><td class="muted">Handlung DE</td><td>'+esc(s.action_physical_de)+'</td></tr><tr><td class="muted">Handlung EN</td><td>'+esc(s.action_physical_en)+'</td></tr></table>':'<p class="muted">Noch leer.</p>')
 +'<details><summary>Felder bearbeiten</summary><form id="cardf"><div class="row"><div class="col">'+field("Einstellungsgröße","shot_size",s.shot_size,"select",[""].concat(V.shotSizes))+'</div><div class="col">'+field("Kamerabewegung","camera_move",s.camera_move,"select",[""].concat(V.cameraMoves))+'</div></div>'
 +field("Objektiv","lens_note",s.lens_note)+field("Licht","lighting",s.lighting)+field("Bildaufbau","composition",s.composition)+field("Handlung (DE)","action_physical_de",s.action_physical_de,"textarea")+field("Handlung (EN, geht an Venice)","action_physical_en",s.action_physical_en,"textarea")
 +'<div class="row"><div class="col">'+engineSelect("Engine","engine",s.engine)+'</div><div class="col">'+field("Workflow","workflow",s.workflow,"select",WORKFLOWS,"r2v_reference: mit Referenzbildern. t2v: nur Text. Wird beim Entwurf automatisch gesetzt.")+'</div></div>'
 +'<div class="row"><div class="col">'+field("Dauer","duration_s",s.duration_s,"select",[5,10])+'</div><div class="col">'+field("Auflösung","resolution",s.resolution,"select",["480p","720p","1080p"])+'</div><div class="col">'+field("Anschluss","transition_in",s.transition_in,"select",["hard_cut","extend"])+'</div></div>'
 +field("Grund für mehr als 480p","resolution_reason",s.resolution_reason)+field("Negativ-Prompt","negative_prompt",s.negative_prompt)+field("Seed","seed",s.seed??"")+'<button class="primary">Felder speichern</button></form></details></div></div>'
 +'<div class="card">'+gateHtml+'</div>'
 +'<details class="card"><summary>Prompt, der an Venice geht</summary><pre>'+esc(s.prompt_final||"(noch nicht gebaut, entsteht bei „Prüfen“)")+'</pre><div id="reqbody"></div></details>'
 +'<div class="card"><h3>Render-Jobs dieses Shots</h3>'+jobsTable(d.jobs)+'</div>'+(d.reviews.length?'<div class="card"><h3>Reviews</h3>'+d.reviews.map(r=>'<div><a href="#review/'+r.id+'">Review #'+r.id+'</a> '+(r.verdict?'<span class="pill '+(r.verdict==="pass"?"green":"red")+'">'+r.verdict+'</span>':'offen')+'</div>').join("")+'</div>':'')
 +'<p class="small muted">Textmodell-Aufrufe für diesen Shot: '+(d.claude_calls.map(c=>esc(c.purpose)+" "+c.input_tokens+"/"+c.output_tokens+" Tokens").join(", ")||"keine")+'</p>';
 $("#beatf").onsubmit=e=>{e.preventDefault();run(()=>api("PATCH","/api/shots/"+id,formData(e.target)))};
 $("#cardf").onsubmit=e=>{e.preventDefault();const o=formData(e.target);o.duration_s=Number(o.duration_s);o.seed=o.seed===""?null:Number(o.seed);run(()=>api("PATCH","/api/shots/"+id,o))};
 $("#bprep").onclick=()=>run(()=>api("POST","/api/shots/"+id+"/prepare"),"Textmodell entwirft … (5 bis 30 Sekunden)");
 $("#bcheck").onclick=()=>run(()=>api("POST","/api/shots/"+id+"/check"),cap.gate?"baue Prompt, Jev prüft …":"baue Prompt, Code prüft …",r=>{const c=r.check;if(!c.built.ok)toast("Prompt nicht gebaut: "+c.built.reason,15000);else if(c.gate)toast("Prüfung "+({green:"grün",yellow:"gelb",red:"rot"})[c.gate.verdict]+(c.gate.reasons.length?":\n"+c.gate.reasons.join("\n"):""),15000);else{const f=c.checks.filter(x=>!x.ok);toast((c.gateError?"Jev nicht erreichbar ("+c.gateError.slice(0,160)+"). ":"")+(f.length?"Code-Prüfung: "+f.map(x=>x.rule+" "+x.detail).join("; "):"Code-Prüfung ohne Befund.")+(cap.gate?"":" Ohne Jev gibt es kein grünes Gate und damit kein Angebot."),20000)}route()});
 $("#bfix").onclick=()=>run(()=>api("POST","/api/shots/"+id+"/review-fix"),"Textmodell korrigiert …");
 $("#bquote").onclick=()=>quote(id,undefined);
 $("#addref").onclick=e=>{e.preventDefault();const tr=document.createElement("tr");tr.setAttribute("data-ref","");tr.innerHTML=refRow({slot:"Image "+($("#reft").querySelectorAll("tr[data-ref]").length+1),reference_id:p.references[0]?.id,role:"identity",subject_label:""},0,p.references).replace(/^<tr data-ref>|<\/tr>$/g,"");$("#reft").appendChild(tr)};
 $("#saveref").onclick=e=>{e.preventDefault();run(()=>api("PUT","/api/shots/"+id+"/references",{references:[...$("#reft").querySelectorAll("tr[data-ref]")].map(tr=>formData(tr))}))};
 m.addEventListener("click",e=>{const b=e.target.closest("[data-del]");if(b){e.preventDefault();b.closest("tr").remove()}});
 bindJobButtons(m);
 const lastJob=d.jobs[0];if(lastJob)$("#reqbody").innerHTML='<h3>Request-Body von Job #'+lastJob.id+' (ohne Bilddaten)</h3><pre>'+esc(JSON.stringify(JSON.parse(lastJob.request_json),null,1))+'</pre>'}
function refRow(r,i,all){return '<tr data-ref><td><input name="slot" value="'+esc(r.slot||"")+'"></td><td><select name="reference_id">'+all.map(x=>'<option value="'+x.id+'"'+(x.id===r.reference_id?" selected":"")+'>#'+x.id+' '+esc(x.kind)+' '+esc(x.path.split(/[\\/]/).pop())+'</option>').join("")+'</select></td><td><select name="role">'+ROLES.map(x=>'<option value="'+x+'"'+(x===r.role?" selected":"")+'>'+esc(ROLE_DE[x])+'</option>').join("")+'</select></td><td><input name="subject_label" value="'+esc(r.subject_label||"")+'" placeholder="Name der Figur"></td><td><button type="button" data-del>×</button></td></tr>'}

// ---------- Jobs ----------
const JOB_DE={quoted:"Angebot liegt vor",approved:"freigegeben",queued:"wird gerendert",done:"fertig",failed:"fehlgeschlagen",needs_consent:"Einwilligung nötig",quote_failed:"Angebot fehlgeschlagen"};
function jobsTable(jobs){if(!jobs.length)return '<p class="muted">Noch keine Jobs. Ein Job entsteht mit „Angebot holen“ auf einer geprüften Shot-Karte.</p>';return '<table><tr><th>Job</th><th>Shot</th><th>Stand</th><th>Preis</th><th>Aktion</th></tr>'+jobs.map(j=>'<tr><td>#'+j.id+'</td><td><a href="#shot/'+j.shot_id+'">Shot '+j.shot_id+'</a></td><td>'+esc(JOB_DE[j.status]||j.status)+(j.error_json?'<br><span class="err small">'+esc(String(j.error_json).slice(0,300))+'</span>':"")+'</td><td>'+(j.quote_usd!=null?j.quote_usd.toFixed(2)+" USD":"–")+'</td><td>'
 +(j.status==="quoted"?'<button class="primary" data-approve="'+j.id+'" data-usd="'+j.quote_usd+'">Freigeben für '+j.quote_usd.toFixed(2)+' USD</button>':"")+(j.status==="approved"?'<button class="primary" data-queue="'+j.id+'">An Venice senden</button>':"")+(j.status==="queued"?'<button data-poll="'+j.id+'">Status abfragen</button>':"")+(j.status==="needs_consent"?'<button data-consent-job="'+j.id+'" data-shot="'+j.shot_id+'">Einwilligung bestätigen</button>':"")+(j.output_path?'<a href="'+esc(fileUrl(j.output_path))+'">Clip öffnen</a>':"")+'</td></tr>').join("")+'</table>'}
function bindJobButtons(m){for(const b of m.querySelectorAll("[data-approve]"))b.onclick=()=>{if(confirm("Job #"+b.dataset.approve+" für "+Number(b.dataset.usd).toFixed(2)+" USD freigeben? Danach wird er mit dem nächsten Klick an Venice gesendet und abgerechnet."))run(()=>api("POST","/api/jobs/"+b.dataset.approve+"/approve"))};
 for(const b of m.querySelectorAll("[data-queue]"))b.onclick=()=>run(()=>api("POST","/api/jobs/"+b.dataset.queue+"/queue"),"sende an Venice …");
 for(const b of m.querySelectorAll("[data-poll]"))b.onclick=()=>run(()=>api("POST","/api/jobs/"+b.dataset.poll+"/poll"),"frage Venice …",r=>{toast(r.job.status==="done"?"Fertig. Review ist offen.":r.job.status==="failed"?"Venice meldet Fehler, siehe Job.":"Noch in Arbeit. In 20 bis 30 Sekunden nochmal abfragen.");route()});
 for(const b of m.querySelectorAll("[data-consent-job]"))b.onclick=()=>{const j=b.dataset.consentJob;api("GET","/api/jobs").then(js=>{const job=js.find(x=>String(x.id)===j);const c=job&&job.error_json?JSON.parse(job.error_json):null;const txt=prompt("Venice verlangt eine Einwilligung für ein Gesicht. Antwort von Venice:\n"+JSON.stringify(c,null,1).slice(0,1500)+"\n\nConsent-Objekt (JSON), das mitgeschickt werden soll:",c&&c.consent?JSON.stringify(c.consent):"");if(!txt)return;quote(Number(b.dataset.shot),JSON.parse(txt))})}}
function quote(shotId,consent){run(()=>api("POST","/api/shots/"+shotId+"/quote",{consent}),"hole Angebot von Venice …",r=>{if(r.result.ok)toast("Angebot: "+r.result.quoteUsd.toFixed(2)+" USD. Freigeben unter Schritt 3: Render-Jobs.",12000);else if(r.result.kind==="needs_consent")toast("Venice verlangt eine Einwilligung für das Gesicht. Unter Schritt 3 bestätigen.",12000);else toast("Angebot fehlgeschlagen: "+JSON.stringify(r.result.error).slice(0,400),15000);route()})}
async function viewJobs(pid){nav(pid);const d=pid?await api("GET","/api/projects/"+pid):{jobs:await api("GET","/api/jobs")};const m=$("#main");
 m.innerHTML='<h1>Schritt 3: Render-Jobs</h1><div class="intro">Jeder Job ist ein Angebot von Venice für einen Shot. <b>Nichts wird gesendet oder abgerechnet, bevor du hier auf Freigeben klickst.</b> Danach: An Venice senden → Status abfragen (das Rendern dauert meist ein bis drei Minuten) → der Clip landet im Review.</div><div class="card">'+jobsTable(d.jobs)+'</div>';
 bindJobButtons(m)}

// ---------- Review ----------
async function viewReview(id){const r=await api("GET","/api/reviews/"+id);nav(r.shot.project_id);const m=$("#main");
 m.innerHTML='<h1>Review · Shot #'+r.shot.seq+'</h1><div class="intro">Links das Referenzfoto, rechts Anfang, Mitte und Ende des Clips. <b>Ist es dieselbe Person? Passiert die Handlung wie beschrieben?</b> Pass nimmt den Shot ab. Fail schickt ihn mit deiner Notiz zurück; eine neue Regel gilt ab dann für alle weiteren Shots.</div>'
 +'<div class="card compare">'+(r.compare_image_path?'<img src="'+esc(fileUrl(r.compare_image_path))+'" alt="Vergleich">':'<p class="muted">Kein Vergleichsbild: ffmpeg fehlt auf diesem Rechner oder der Shot hat keine Identitätsreferenz. Der Clip selbst ist unten.</p>')+'</div>'
 +'<div class="card"><div class="frames">'+r.frames.map(p=>'<img src="'+esc(fileUrl(p))+'" alt="">').join("")+'</div>'+(r.job&&r.job.output_path?'<video src="'+esc(fileUrl(r.job.output_path))+'" controls style="max-width:100%;margin-top:8px"></video>':"")+'</div>'
 +'<div class="card"><h3>Checkliste</h3><form id="vf"><table>'+r.checklist.map(c=>'<tr><td><b>'+esc(c.rule)+'</b></td><td>'+esc(c.text_de)+'</td><td><select data-ck="'+esc(c.rule)+'"><option value="">–</option><option value="1"'+(c.pass===true?" selected":"")+'>ok</option><option value="0"'+(c.pass===false?" selected":"")+'>nicht ok</option></select></td></tr>').join("")+'</table>'
 +field("Notiz","notes",r.notes,"textarea",null,"Bei Fail: was ist falsch? Die Notiz steht danach auf der Shot-Karte.")+'<details><summary>Neue Regel aus diesem Review</summary>'+field("Regel","nr_de","","input",null,"Gilt ab jetzt für alle weiteren Shots und steht im Jev-Gate.","z. B. Die Narbe über der linken Braue muss sichtbar sein.")+field("Schwere","nr_sev","block","select",["block","warn"])+'</details>'
 +(r.verdict?'<p>Urteil: <span class="pill '+(r.verdict==="pass"?"green":"red")+'">'+r.verdict+'</span></p>':'<button type="button" class="primary big" id="pass">Pass</button><button type="button" class="danger big" id="fail">Fail → zurück zum Entwurf</button>')+'</form></div>';
 const send=v=>{const o=formData($("#vf"));const checklist=[...m.querySelectorAll("[data-ck]")].map(s=>({rule:s.dataset.ck,pass:s.value===""?null:s.value==="1"}));run(()=>api("POST","/api/reviews/"+id+"/verdict",{verdict:v,notes:o.notes,checklist,new_rule:{text_de:o.nr_de,text_en:"",severity:o.nr_sev}}),null,()=>{location.hash="shot/"+r.shot.id})};
 if($("#pass")){$("#pass").onclick=()=>send("pass");$("#fail").onclick=()=>send("fail")}}
</script></body></html>`;
